
version: "2.3"

# 请修改这里的环境变量
x-env: &env
  environment:
    - TZ=Asia/Shanghai
    # root账户
    - MYSQL_USER=root
    # root账户密码
    - MYSQL_PASS=88888888
    # mysql的IP地址
    - MYSQL_IP=127.0.0.1
    # 拥有管理员权限的游戏账号
    - ADMIN_USER=123456789
    # 启动模式
    - MODE=default # default：与docker服务端配合模式  standalone：独立部署模式  utils：工具模式
    # 提高java内存上限，防止读取pvf内存溢出
    - JAVA_OPTS=-Xmx8g -Xms512m


services:
  dnfadmin:
    image: registry.cn-hangzhou.aliyuncs.com/gebilaoyu/dnf-admin:1.0.3
    ports:
      - 8888:8888
    <<: *env
    volumes:
      - /data/dnf:/data
    privileged: true
    restart: unless-stopped
    container_name: dnfadmin

