
server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true


mybatis-flex:
  datasource:
    d_taiwan:
      url: jdbc:mysql://${MYSQL_HOST:121.36.64.134}:${MYSQL_PORT:3306}/d_taiwan?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
    taiwan_cain:
      url: jdbc:mysql://${MYSQL_HOST:121.36.64.134}:${MYSQL_PORT:3306}/taiwan_cain?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
