
server:
  port: 8888
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*,text/javascript

spring:
  servlet:
    multipart:
      #限制报文大小，post请求大小限制,undertow里的设置不会生效
      max-request-size: 1000MB
      max-file-size: 1000MB
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  web:
    resources:
      static-locations: classpath:/static/
  liquibase:
    enabled: true
    databaseChangeLogTable: "da_database_change_log"
    databaseChangeLogLockTable: "da_database_change_log_lock"

mybatis-flex:
  datasource:
    d_taiwan:
      type: druid
      url: jdbc:mysql://${MYSQL_HOST:dnfmysql}:${MYSQL_PORT:3306}/d_taiwan?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
      connectionInitSqls:
        - SET NAMES utf8
    taiwan_cain:
      type: druid
      url: jdbc:mysql://${MYSQL_HOST:dnfmysql}:${MYSQL_PORT:3306}/taiwan_cain?useUnicode=true&characterEncoding=latin1&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
      connectionInitSqls:
        - SET NAMES latin1
    taiwan_cain_2nd:
      type: druid
      url: jdbc:mysql://${MYSQL_HOST:dnfmysql}:${MYSQL_PORT:3306}/taiwan_cain_2nd?useUnicode=true&characterEncoding=latin1&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
      connectionInitSqls:
        - SET NAMES latin1
    taiwan_login:
      type: druid
      url: jdbc:mysql://${MYSQL_HOST:dnfmysql}:${MYSQL_PORT:3306}/taiwan_login?useUnicode=true&characterEncoding=latin1&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
      connectionInitSqls:
        - SET NAMES latin1
    taiwan_billing:
      type: druid
      url: jdbc:mysql://${MYSQL_HOST:dnfmysql}:${MYSQL_PORT:3306}/taiwan_billing?useUnicode=true&characterEncoding=latin1&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
      connectionInitSqls:
        - SET NAMES latin1
    taiwan_game_event:
      type: druid
      url: jdbc:mysql://${MYSQL_HOST:dnfmysql}:${MYSQL_PORT:3306}/taiwan_billing?useUnicode=true&characterEncoding=latin1&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
      connectionInitSqls:
        - SET NAMES latin1
  configuration:
    call-setters-on-nulls:
da:
  admin-user: ${ADMIN_USER:123456789}
  admin-role: ${ADMIN_ROLE:admin}
  current-version: 2024.02.27
  mode: ${MODE:default} # default：与docker服务端配合模式  standalone：独立部署模式  utils：工具模式
  standalone-disable-resource:
    - "channel"
    - "channel.frida"
    - "tool.restartServer"
    - "tool.restartDb"
    - "tool.restartDa"
    - "tool.generateKeyPem"
  utils-disable-resource:
    - "notice"
    - "notice.sendNotice"
    - "channel"
    - "channel.frida"
    - "gameEvent"
    - "tool.restartServer"
    - "tool.startGame"
    - "tool.restartDb"
    - "tool.restartDa"
    - "tool.generateKeyPem"
    - "gameEvent"
    - "gameEvent.remove"

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # jwt秘钥
  jwt-secret-key: ${random.uuid}
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 36000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: tik
  # 是否输出操作日志
  is-log: true

#management:
#  server:
#    port: 8689
#  metrics:
#    tags:
#      application: ${spring.application.name}
#  endpoints:
#    web:
#      exposure:
#        include:
#          - health
#          - prometheus

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: plus.easydo.dnf.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

management:
  server:
    port: 8689
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include:
          - health
