
server:
  port: 8888

spring:
  servlet:
    multipart:
      #限制报文大小，post请求大小限制,undertow里的设置不会生效
      max-request-size: 200MB
      max-file-size: 500MB
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  web:
    resources:
      static-locations: classpath:/static/
  liquibase:
    enabled: true
    databaseChangeLogTable: "da_database_change_log"
    databaseChangeLogLockTable: "da_database_change_log_lock"

mybatis-flex:
  datasource:
    d_taiwan:
      type: druid
      url: jdbc:mysql://${MYSQL_HOST:dnfmysql}:${MYSQL_PORT:3306}/d_taiwan?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
      connectionInitSqls:
        - SET NAMES utf8
    taiwan_cain:
      type: druid
      url: jdbc:mysql://${MYSQL_HOST:dnfmysql}:${MYSQL_PORT:3306}/taiwan_cain?useUnicode=true&characterEncoding=latin1&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
      connectionInitSqls:
        - SET NAMES latin1
    taiwan_cain_2nd:
      type: druid
      url: jdbc:mysql://${MYSQL_HOST:dnfmysql}:${MYSQL_PORT:3306}/taiwan_cain_2nd?useUnicode=true&characterEncoding=latin1&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:88888888}
      connectionInitSqls:
        - SET NAMES latin1
  configuration:
    call-setters-on-nulls:

admin: ${ADMIN_USER:123456789}
dpGmKey: ${DP_GM_KEY:123456789}
pvfPath: ${PVF_PATH:/data/server/data/Script.pvf}

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # jwt秘钥
  jwt-secret-key: ${JWT_SECRET_KEY:123456789qweasdzxc}
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 3600
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: tik
  # 是否输出操作日志
  is-log: true
